### PR TITLE
Support for new RedisJSON Commands for queries (JSON.INDEX, JSON.QGET)

### PR DESCRIPTION
**Pull request by Cupcakus**

### CODE REVIEW

**Review by gkorland — APPROVED** [review]

**Comment by collin-thomas** [comment]
Would you please merge these changes?  @stockholmux @gkorland

**Comment by OmgImAlexis** [comment]
I'm not seeing any references to `JSON.INDEX` or `JSON.QGET` on https://oss.redislabs.com/redisjson/commands/

@collin-thomas any chance you have a link to these new commands?

**Comment by collin-thomas** [comment]
@OmgImAlexis I'm struggling to find where I read about them, it's probably on my work computer. I did find this response on an issue on the RedisJSON repo that talks about they are unofficial commands [https://github.com/RedisJSON/RedisJSON/issues/304#issuecomment-822253455](https://github.com/RedisJSON/RedisJSON/issues/304#issuecomment-822253455) I would have to check closer, but my guess is they were deprecated and have since been removed.

**Comment by OmgImAlexis** [comment]
@Cupcakus any chance you have any insight? This may need to be closed.

**Comment by Cupcakus** [comment]
Yes, it looks like these functions were deprecated, I'll close the PR.

**Pull request closed without merging**
